server:
  dev:
    enabled: false
  standalone:
    enabled: true
  dataStorage:
    enabled: true
    size: 1Gi
    storageClass: gp3
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi
  readinessProbe:
    enabled: true
    path: /v1/sys/health?standbyok=true
  livenessProbe:
    enabled: true
    path: /v1/sys/health?standbyok=true

ui:
  enabled: true
