# Generated by Django 5.2.5 on 2025-08-23 00:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voicepay_auth", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="voiceuser",
            name="full_name",
        ),
        migrations.AddField(
            model_name="voiceuser",
            name="first_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="voiceuser",
            name="last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="voiceuser",
            name="voice_embedding",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
