name: CI

on:
  push:
    branches: [dev, prod]
  pull_request:
    branches: [dev, prod]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: CI passed
        run: echo "Pipeline ran successfully"

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t voicepay-auth ./services/auth

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/auth

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install -r requirements.txt pytest pytest-django

      - name: Run tests
        run: pytest

  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install yamllint
        run: pip install yamllint

      - name: Run yamllint
        run: yamllint -c .yamllint .

  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/auth

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install linting tools
        run: pip install black==23.9.1 flake8

      - name: Run black
        run: black --check .

      - name: Run flake8
        run: flake8 .
